-   id: generate-changelog
    name: generate changlog from folder
    entry: generate-changelog
    language: system
    files: ^(changelog|changelogs)/.*\.(yml|yaml)$
    types: [yaml]
    stages: [commit, push, manual]
