default_language_version:
    python: python3.8
fail_fast: false
minimum_pre_commit_version: 2.3.0
repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: 41e26ab636aab10b8b367c9654d606604c0e5da8
        hooks:
            -   id: check-json
                files: .json$
            -   id: check-toml
                files: .toml$
            -   id: check-yaml
                files: .(yaml|yml)$
    -   repo: https://github.com/pre-commit/pre-commit
        rev: 0c481ea51dc695893bfcba8d3483a78e9b2c0575
        hooks:
            -   id: validate_manifest
    -   repo: https://github.com/asottile/setup-cfg-fmt
        rev: v1.9.0
        hooks:
            -   id: setup-cfg-fmt
    -   repo: local
        hooks:
            -   id: hadolint
                name: Valid Dockerfile
                description: Valid Dockerfile
                language: docker_image
                types:
                    - dockerfile
                entry: --entrypoint /bin/hadolint hadolint/hadolint:latest --ignore DL3013 --ignore SC2102 --ignore DL3018 --ignore DL3008
#            -   id: generate-changelog
#                name: generate changlog from folder
#                entry: pre-commit-generate-changelog
#                language: system
#                types: [yaml]
#    -   repo: https://github.com/smian/pre-commit-makefile
#        rev: 261f8fb4b31dfdc05d1a1d7fbde1f1462ecde66d
#        hooks:
#            -   id: makefile-doc
#    -   repo: https://github.com/igorshubovych/markdownlint-cli
#        rev: 794167ae7af3a4c4d742bc0669ec916d92188c1f
#        hooks:
#            -   id: markdownlint
#                args: ['--fix']
    -   repo: https://github.com/asottile/pyupgrade
        rev: c0c8f47257ad19a9ac0caaa9948847fce1c4439b
        hooks:
            -   id: pyupgrade
                args: ['--py3-only', '--py37-plus']
#    -   repo: https://github.com/asottile/seed-isort-config
#        rev: v2.1.1
#        hooks:
#            -   id: seed-isort-config
#    -   repo: https://github.com/timothycrosley/isort
#        rev: 3e09facb2311f5b5b8bff8da90f4992e57f4bc9e
#        hooks:
#            -   id: isort
#                args: ['--settings-path=./setup.cfg']
    -   repo: https://github.com/psf/black
        rev: 7a14a37981862ef418f3cdb4a7e2375856f97529
        hooks:
            -   id: black
                args: ['--config=./black.toml']
#    -   repo: https://gitlab.com/pycqa/flake8
#        rev: 0c3b8045a7b51aec7abf19dea94d5292cebeeea0
#        hooks:
#            -   id: flake8
#                args: ['--config=./setup.cfg']
#    -   repo: https://github.com/pre-commit/mirrors-pylint
#        rev: v2.5.0
#        hooks:
#            -   id: pylint
#                args: ['--rcfile=./setup.cfg']
#    -   repo: https://github.com/asottile/dead
#        rev: v1.3.0
#        hooks:
#            -   id: dead
#                args: ['--files=pre_commit_hook/']
#    -   repo: https://github.com/pre-commit/mirrors-mypy
#        rev: v0.770
#        hooks:
#            -   id: mypy
#                args: ['--config-file=./setup.cfg']
#    -   repo: https://github.com/pre-commit/pre-commit-hooks
#        rev: 41e26ab636aab10b8b367c9654d606604c0e5da8
#        hooks:
#            -   id: check-ast
#            -   id: check-case-conflict
#            -   id: check-docstring-first
#            -   id: debug-statements
#            -   id: end-of-file-fixer
#            -   id: fix-encoding-pragma
#                args: [--remove]
#            -   id: mixed-line-ending
#                args: [--fix=lf]
#            -   id: trailing-whitespace
#    -   repo: https://github.com/pre-commit/pre-commit-hooks
#        rev: 41e26ab636aab10b8b367c9654d606604c0e5da8
#        hooks:
#            -   id: check-merge-conflict
